#!/bin/bash

# setup wireguard

sudo apt-get update

wget -O wireguard.sh https://get.vpnsetup.net/wg

sudo bash wireguard.sh --auto



# setup script

# wget -o wg-peer.sh https://github.com/earlzdev/VpnConfiguringSciprts.git

sudo chmod +x wg-peer.sh



# setup software

git clone https://github.com/earlzdev/WgBackend.git

cd WgBackend

apt install uvicorn

apt install python3-pip

pip install "fastapi[all]"

pip install -r requirements.txt

nohup uvicorn main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &